name: student_schedule
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluent_ui: ^3.12.0
  provider: ^6.0.3
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.0.15
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  windows:
    generate: true
    image_path: "assets/app-icon/icon.png"
    icon_size: 48

flutter:

  uses-material-design: true

  assets:
    - assets/images/